-- MySQL Script generated by MySQL Workbench
-- Tue Aug 22 05:58:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Senior f_ PHP_d_ symfony
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Senior f_ PHP_d_ symfony
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Senior f_ PHP_d_ symfony` DEFAULT CHARACTER SET utf8 ;
USE `Senior f_ PHP_d_ symfony` ;

-- -----------------------------------------------------
-- Table `Senior f_ PHP_d_ symfony`.`Link_domain_and_module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Senior f_ PHP_d_ symfony`.`Link_domain_and_module` ;

CREATE TABLE IF NOT EXISTS `Senior f_ PHP_d_ symfony`.`Link_domain_and_module` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name_domen` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `Name_module` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
